remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

#nav config
nav:
  -text:Home
  url:/data.html



#Author config
author:
    name: handong1587
    email: handong1587@gmail.com
    imageLink: /images/header2.jpg
    simpleIntro: Hi world~
    detailIntro:
      <p>I am working as machine learning/deep learning engineer.</p>
      <p>This blog is used to organise interesting papers, projects, websites, blogs and my reading/study notes.</p>
      <p>Feel free to send PRs or open issues to help maintain this blog&#58; https://github.com/handong1587/handong1587.github.io</p>
      <p></p>
